name: Repository maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    uses: ObsidianPublisher/actions/.github/workflows/maintenance.yml@main
    with:
      CLEAN: false
      DRY_RUN: false
      BRANCH: master
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      AUTHOR_NAME: Hifumi
      AUTHOR_EMAIL: hifumi@peroro.club
