name: Get latest release from template

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: false
      BASE_BRANCH: master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTHOR_NAME: Hifumi
      AUTHOR_EMAIL: hifumi@peroro.club
